remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Natalia Dudina â€“ Project Portfolio
description: High-impact operations & automation projects across Europe.

